variables:
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    NODE_OPTIONS: --max_old_space_size=3072

stages:
    - deploy

cache:
    paths:
        - .npm/
    key: ${CI_COMMIT_REF_SLUG}


.deploy-template: &deploy-definition
    image: timezynk/web-deploy
    cache:
        paths:
            - ~/.cache/pip
    script:
        - echo "hello"
    tags:
        - timezynkServer

deploy-release:
    stage: deploy
    <<: *deploy-definition
    rules:
        - if: $CI_COMMIT_TAG =~ /^v.*/
          when: on_success
        - when: never
